### ISSUE TITLE
Move SafeCast to core

### ISSUE THREAD

**Issue by hensha256** [Uniswap/v4-periphery#223] opened 2024-07-29 22:09 UTC
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

SafeCast lib in periphery has just 1 function - we need it in periphery to make sure it gets audited. However post audits we should move it into SafeCast in core

**Comment by saucepoint** [comment] 2024-09-04 22:06
duplicate of https://github.com/Uniswap/v4-periphery/issues/305

**Closed by saucepoint** 2024-09-04 22:06 UTC
Labels: post-audit
