### ISSUE TITLE
Introduce bytes[] parmeter to all hooks.

### ISSUE THREAD

**Issue by RitzyDevBox** [Uniswap/v4-periphery#41] opened 2023-07-07 23:00 UTC
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

External protocols may want to provide additional information to the hooks that would be provided from the frontend when users make invoke existing defi actions (swap, provide lp, etc...).  

### Describe the desired implementation.

each method in the hook interfaces should provide a bytes[] calldata optionalParams, which can be parsed by pools implementation.

### Describe alternatives.

Currently this can be done by creating a custom contract with a tstore to provide data. However, this would force protocols to create a new contracts, instead of leveraging this field directly from the universal router, by providing optional params there will be more flexiblity in the implementation.

### Additional context.

Currently the bytes[] parameter is limited due to the limitations of deserialization, certain nested data may require an external contract,  Regardless, this parameter would cover a vast majority of the implementations, and help by preventing developers from having to provide custom contracts to store the data.

**Comment by saucepoint** [comment] 2024-09-04 22:34
duplicate of https://github.com/Uniswap/v4-core/issues/307

**Closed by saucepoint** 2024-09-04 22:34 UTC
